/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package backend

class Library {
  def someLibraryMethod(): Boolean = true
}

object Main {
  def main(args: Array[String]) = {
    println("fuck")
    ()
  }
}
